module.exports = {
  "DATA_SOURCE_ID": "_id",
  "DATA_SOURCE_DATA": "data",
  "DATA_SOURCE_CACHE": "cache",
  "FORM_ID": "_id",
  "FORM_NAME": "name",
  FORM_UPDATED_BY: "updatedBy",
  FORM_LAST_UPDATED: "lastUpdated",
  DATA_SOURCE_TYPE_SERVICE: "service",
  DATA_SOURCE_TYPE_EXTERNAL: "external",
  DATA_TARGET_TYPE_POST_PROCESSING: "postProcessing",
  DATA_TARGET_TYPE_REAL_TIME: "realTime",
  ERROR_CODES: {
    FH_FORMS_NOT_FOUND: "FH_FORMS_NOT_FOUND",
    FH_FORMS_INVALID_PARAMETERS: "FH_FORMS_INVALID_PARAMETERS",
    FH_FORMS_UNEXPECTED_ERROR: "FH_FORMS_UNEXPECTED_ERROR",
    FH_FORMS_ERR_CODE_NOT_SET: "FH_FORMS_ERR_CODE_NOT_SET",
    FH_FORMS_ERR_CODE_PDF_GENERATION: "FH_FORMS_ERR_PDF_GENERATION",
    FH_FORMS_ERR_CODE_SUBMISSION_EXPORT: "FH_FORMS_ERR_SUBMISSION_EXPORT"
  },
  MIDDLEWARE: {
    resultTypes: {
      forms: "formsResult",
      themes: "themesResult",
      submissions: "submissionsResult",
      formProjects: "formsProjectsResult",
      formProjectsConfig: "formsProjectsConfigResult",
      dataSources: "dataSourcesResult",
      dataTargets: "dataTargetsResult",
      themeTemplate: "themeTemplate",
      formTemplate: "formTemplate"
    }
  },
  FORM_CONSTANTS: {
    DATA_SOURCE_TYPE_STATIC: "static",
    DATA_SOURCE_TYPE_DATA_SOURCE: "dataSource",
    FIELD_TYPE_CHECKBOXES: "checkboxes",
    FIELD_TYPE_RADIO: "radio",
    FIELD_TYPE_DROPDOWN: "dropdown",
    FIELD_TYPE_TEXT: "text",
    FIELD_TYPE_TEXT_AREA: "textarea",
    FIELD_TYPE_URL: "url",
    FIELD_TYPE_NUMBER: "number",
    FIELD_TYPE_EMAIL: "emailAddress",
    FIELD_TYPE_LOCATION: "location",
    FIELD_TYPE_MAP: "locationMap",
    FIELD_TYPE_PHOTO: "photo",
    FIELD_TYPE_SIGNATURE: "signature",
    FIELD_TYPE_FILE: "file",
    FIELD_TYPE_DATE_TIME: "dateTime",
    FIELD_TYPE_SECTION_BREAK: "sectionBreak",
    FIELD_TYPE_MATRIX: "matrix",
    FIELD_TYPE_BARCODE: "barcode",
    FIELD_TYPE_SLIDER_NUMBER: "sliderNumber",
    FIELD_TYPE_READ_ONLY: "readOnly"
  },
  MODELNAMES: {
    FORM: "Form",
    PAGE: "Page",
    FIELD: "Field",
    THEME: "Theme",
    FIELD_RULE : "FieldRule",
    PAGE_RULE: "PageRule",
    APP_FORMS: "AppForms",
    APP_THEMES: "AppThemes",
    FORM_SUBMISSION: "FormSubmission",
    GROUPS: "Groups",
    APP_CONFIG: "AppConfig",
    DATA_SOURCE: "DataSource",
    DATA_SOURCE_CACHE: "DataSourceCache",
    DATA_TARGET: "DataTarget",
    DATA_SOURCE_AUDIT_LOG: "DataSourceAuditLog"
  },
  SCHEMA_OPTIONS: { strict: true,  versionKey: false  },
  SCHEMA_OPTIONS_NO_ID: { strict: true,  versionKey: false , _id: false },
  SUBMISSION_STATUS: {
    COMPLETE: 'complete',
    PENDING: 'pending',
    ERROR: 'error'
  },
  SUBMISSION_SUMMARY_FIELD_SELECTION: {"formSubmittedAgainst.pages": 0, "formSubmittedAgainst.fieldRules": 0, "formSubmittedAgainst.pageRules": 0, "formSubmittedAgainst.fieldRef": 0, "formSubmittedAgainst.pageRef": 0},
  FIELD_TYPES_INCLUDED_IN_SUMMARY: ["text", "textarea", "number", "emailAddress", "dropdown", "radio", "dateTime"],
  SUBMISSIONS_FILTER_FIELDS: ['_id', 'updatedBy', 'appId', 'appClientId', 'appCloudName', 'appEnvironment', 'formSubmittedAgainst.name', 'formId', 'userId', 'deviceId', 'deviceIPAddress'],
  NUM_FIELDS_INCLUDED_IN_SUMMARY: 3
};
